name: prepare publish check

on:
  pull_request:
    branches:
      - develop
      - main

# env:
#   FBBE_type:  ${{ vars.FBBE_type }}
#   FBBE_project_id:  ${{ vars.FBBE_project_id }}
#   FBBE_private_key_id:  ${{ vars.FBBE_private_key_id }}
#   FBBE_private_key:  ${{ vars.FBBE_private_key }}
#   FBBE_client_email:  ${{ vars.FBBE_client_email }} 
#   FBBE_client_id:  ${{ vars.FBBE_client_id }}
#   FBBE_auth_uri:  ${{ vars.FBBE_auth_uri }}
#   FBBE_token_uri:  ${{ vars.FBBE_token_uri }}
#   FBBE_auth_provider_x509_cert_url:  ${{ vars.FBBE_auth_provider_x509_cert_url }}
#   FBBE_client_x509_cert_url:  ${{ vars.FBBE_client_x509_cert_url }}
#   FBBE_universe_domain:  ${{ vars.FBBE_universe_domain }}
#   NEXT_PUBLIC_FBFE_apiKey: ${{ vars.NEXT_PUBLIC_FBFE_apiKey }}
#   NEXT_PUBLIC_FBFE_authDomain: ${{ vars.NEXT_PUBLIC_FBFE_authDomain }}
#   NEXT_PUBLIC_FBFE_projectId: ${{ vars.NEXT_PUBLIC_FBFE_projectId }}
#   NEXT_PUBLIC_FBFE_storageBucket: ${{ vars.NEXT_PUBLIC_FBFE_storageBucket }}
#   NEXT_PUBLIC_FBFE_messagingSenderId: ${{ vars.NEXT_PUBLIC_FBFE_messagingSenderId }}
#   NEXT_PUBLIC_FBFE_appId: ${{ vars.NEXT_PUBLIC_FBFE_appId }}
#   NEXT_PUBLIC_FBFE_measurementId: ${{ vars.NEXT_PUBLIC_FBFE_measurementId }}

jobs:

  install-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install packages
        run: yarn
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}

  check-format:
    runs-on: ubuntu-latest
    needs: [install-package]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Reuse node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}
      - name: check format
        run: yarn check-format
  
  check-lint:
    runs-on: ubuntu-latest
    needs: [install-package]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Reuse node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}
      - name: check lint
        run: yarn check-lint
  
  check-types:
    runs-on: ubuntu-latest
    needs: [install-package]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Reuse node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}
      - name: check types
        run: yarn check-types

  check-build:
    runs-on: ubuntu-latest
    needs: [install-package, check-types, check-format, check-lint]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Reuse node modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ github.sha }}
      - name: check build next
        run: yarn build